"""Generate deckkit/widths.py: advance widths (1/1000 em) for common Office fonts.

Dev-time tool. Needs Pillow and the font files (present on macOS). The generated
module is plain data, so deckkit itself needs no font files and no Pillow.

    .venv/bin/python tools/gen_width_tables.py
"""
from __future__ import annotations

import pathlib

from PIL import ImageFont

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "skills" / "deck-build" / "scripts" / "deckkit" / "widths.py"
FONT_DIR = pathlib.Path("/System/Library/Fonts/Supplemental")

FONTS = {
    "arial": "Arial.ttf",
    "arial bold": "Arial Bold.ttf",
    "georgia": "Georgia.ttf",
    "georgia bold": "Georgia Bold.ttf",
    "verdana": "Verdana.ttf",
    "verdana bold": "Verdana Bold.ttf",
    "tahoma": "Tahoma.ttf",
    "tahoma bold": "Tahoma Bold.ttf",
    "trebuchet ms": "Trebuchet MS.ttf",
    "trebuchet ms bold": "Trebuchet MS Bold.ttf",
    "times new roman": "Times New Roman.ttf",
    "times new roman bold": "Times New Roman Bold.ttf",
}

EXTRA = "–—‘’“”•…€₩¥£×÷≤≥→←↑↓°±‰Δ✓·"
CHARS = "".join(chr(c) for c in range(32, 127)) + "".join(chr(c) for c in range(160, 256)) + EXTRA


def table(path: pathlib.Path) -> str:
    font = ImageFont.truetype(str(path), 1000)
    return ",".join(str(round(font.getlength(ch))) for ch in CHARS)


def main() -> None:
    lines = [
        '"""Advance widths in 1/1000 em. Generated by tools/gen_width_tables.py. Do not edit."""',
        "",
        f"CHARS = {CHARS!r}",
        "",
        "TABLES = {",
    ]
    for name, file in FONTS.items():
        lines.append(f"    {name!r}: {table(FONT_DIR / file)!r},")
    lines += ["}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(FONTS)} fonts, {len(CHARS)} chars)")


if __name__ == "__main__":
    main()
